on:
  push:
    branches:
    - master

jobs:
  cloc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        path: master
    - name: show current directory
      run: pwd
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install -y cloc
    - name: calculate count of code line
      run: |
        cloc . --out=report.out
    - name: checkout cloc branch
      uses: actions/checkout@v3
      with: 
        path: cloc
        ref: cloc
    - name: show current directory
      run: pwd
    - name: commit cloc file 
      run: |
        git config --global user.name "cloc"
        git config --global user.email "cloc@github.com"
        cp /home/runner/work/react-basic-movie-app/react-basic-movie-app/report.out .
        git add report.out
        git commit -am "auto-update cloc file"
    - name: push cloc commits forcefully
      run: |
        git push origin cloc --force
