on:
  push:
    branches:
    - master

jobs:
  cloc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        apt update
        apt install -y cloc
    - name: calculate count of code line
      run: |
        cloc . --out=report.out
    - name: checkout cloc branch and commit
      run: |
        git config --global user.name="cloc"
        git config --global user.email="cloc@github.com"
        git checkout cloc
        git add report.out
        git commit -am "auto-update cloc file"
    - name: push cloc commits forcefully
      run: |
        git push origin cloc --force
      
