on:
  push:
    branches:
    - master

jobs:
  cloc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: show current directory
      run: pwd
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install -y cloc
    - name: calculate count of code line
      run: |
        cloc . --out=report.out
    - name: commit cloc file 
      run: |
        git config --global user.name "cloc"
        git config --global user.email "cloc@github.com"
        git add report.out
        git commit -am "auto-update cloc file"
